/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class comChat_ChatController */

#ifndef _Included_comChat_ChatController
#define _Included_comChat_ChatController
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     comChat_ChatController
 * Method:    initPort
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_comChat_ChatController_initPort
  (JNIEnv *, jclass, jstring);

/*
 * Class:     comChat_ChatController
 * Method:    sendMessage
 * Signature: (ILjava/lang/String;I)V
 */
JNIEXPORT void JNICALL Java_comChat_ChatController_sendMessage
  (JNIEnv *, jclass, jint, jstring, jint);

/*
 * Class:     comChat_ChatController
 * Method:    closePort
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_comChat_ChatController_closePort
  (JNIEnv *, jclass, jint);

/*
 * Class:     comChat_ChatController
 * Method:    readSymbol
 * Signature: (I)C
 */
JNIEXPORT jchar JNICALL Java_comChat_ChatController_readSymbol
  (JNIEnv *, jclass, jint);

#ifdef __cplusplus
}
#endif
#endif
