/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class comChat_PortThread */

#ifndef _Included_comChat_PortThread
#define _Included_comChat_PortThread
#ifdef __cplusplus
extern "C" {
#endif
#undef comChat_PortThread_MIN_PRIORITY
#define comChat_PortThread_MIN_PRIORITY 1L
#undef comChat_PortThread_NORM_PRIORITY
#define comChat_PortThread_NORM_PRIORITY 5L
#undef comChat_PortThread_MAX_PRIORITY
#define comChat_PortThread_MAX_PRIORITY 10L
/*
 * Class:     comChat_PortThread
 * Method:    initPort
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_comChat_PortThread_initPort
  (JNIEnv *, jobject, jstring);

/*
 * Class:     comChat_PortThread
 * Method:    sendMessage
 * Signature: (ILjava/lang/String;I)V
 */
JNIEXPORT void JNICALL Java_comChat_PortThread_sendMessage
  (JNIEnv *, jobject, jint, jstring, jint);

/*
 * Class:     comChat_PortThread
 * Method:    closePort
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_comChat_PortThread_closePort
  (JNIEnv *, jobject, jint);

/*
 * Class:     comChat_PortThread
 * Method:    readSymbol
 * Signature: (I)C
 */
JNIEXPORT jchar JNICALL Java_comChat_PortThread_readSymbol
  (JNIEnv *, jobject, jint);

/*
 * Class:     comChat_PortThread
 * Method:    setOptions
 * Signature: (IIIZ)V
 */
JNIEXPORT void JNICALL Java_comChat_PortThread_setOptions
  (JNIEnv *, jobject, jint, jint, jint, jboolean);

#ifdef __cplusplus
}
#endif
#endif
